export class TransactionDetail {
  transactionId: Number;
  buySell: String;  
  commAmt: Number;
  commRate: Number;
  diffCommRate: Number;
  delCommRate: Number;
  entryDatetime: Date;
  grossAmt: Number;
  loadDatetime: Date;
  manual: String;
  netAmt: Number;  
  posted: Boolean;
  price: number;
  processed: Boolean;
  remarks: String;
  sensitive: Boolean;  
  terminalId:String;
  ticketNo: String;
  transDate: Date;
  volume: number;  
  refParticipantId:Number;
  refParticipantCode:String;
  participantId: Number;
  participantCode: String;
  buyerClientId: Number;
  clientCode: String;
  clientId: Number;
  buyerClientCode: String;
  sellerClientId: Number;
  sellerClientCode: String;
  exchangeId: number;
  exchangeCode:String;
  exchangeName:String;
  marketId: number;
  marketCode:String;
  securityId:number;
  securityName:String;
  symbol: String;  
  settlementCalendarId: Number;
  settlementDate: Date;
  startDate:Date;
  endDate:Date;
  settlementTypeId:Number;
  settlementType:String;  
  traansactionTypeId: number;
  traansactionTypeCode:String;
  commFlag:String;  
  code:String;  
  fcRate: number;
  fcAmount: Number;  
  fcDays: number;  
  c2c:Boolean;
  c2cCode:String;
  badlaDate: Date;
  mtmLossPercentage: Number;
}
